# Generated by Django 4.2.9 on 2024-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_businessprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrapeJsTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_data', models.JSONField()),
            ],
        ),
    ]
